-- Futuro 2026/27 reference data and first-team fixtures for the official site.
-- Staging only. Do not run against production.
-- GENERATED by scripts/import-futuro-data.mjs from data/futuro/*.csv. Do not edit by hand;
-- fix the CSV or the script and regenerate. How to apply: docs/futuro-data-import.md.
--
-- Idempotent: clubs and venues upsert by slug (a value in the CSV wins; an empty CSV cell keeps
-- what an admin entered), standings by (season, competition, round, club),
-- fixtures are matched by season + competition + round or by team + kickoff and only filled in,
-- never duplicated. Rows that did not change are not touched. A second run changes nothing.
-- Fixtures are imported unpublished (is_published = false) for an admin to review; they never
-- set training_sessions.venue_id (QR check-in).

begin;

do $$
begin
  if (select count(*) from public.teams where kind = 'competition_team' and layer_key = 'senior' and age_band = 'senior' and status = 'active') <> 1 then
    raise exception 'expected exactly one active senior first team (台中FUTURO 一線隊)';
  end if;
  if not exists (select 1 from public.seasons where label = '2026/27') then
    raise exception 'season 2026/27 missing (migration 20261009110000_site_public_api_v1.sql)';
  end if;
  if not exists (select 1 from public.competitions where slug = 'tfpl') then
    raise exception 'competition tfpl missing (migration 20261009110000_site_public_api_v1.sql)';
  end if;
end
$$;

-- Venues (9) ---------------------------------------------------------------------
insert into public.public_venues (slug, name_zh, name_en, address_zh, address_en, lat, lng, map_url, transit_zh, parking_zh, accessibility_zh, capacity, surface)
values
  ('xitun-football-field', '台中西屯足球場', null, '臺中市西屯區朝馬路520號', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E5%8F%B0%E4%B8%AD%E8%A5%BF%E5%B1%AF%E8%B6%B3%E7%90%83%E5%A0%B4%20%E8%87%BA%E4%B8%AD%E5%B8%82%E8%A5%BF%E5%B1%AF%E5%8D%80%E6%9C%9D%E9%A6%AC%E8%B7%AF520%E8%99%9F', null, null, null, null, 'artificial'),
  ('taiyuan-football-field', '太原足球場', null, '臺中市北屯區建軍一街6-8號', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E5%A4%AA%E5%8E%9F%E8%B6%B3%E7%90%83%E5%A0%B4%20%E8%87%BA%E4%B8%AD%E5%B8%82%E5%8C%97%E5%B1%AF%E5%8D%80%E5%BB%BA%E8%BB%8D%E4%B8%80%E8%A1%976-8%E8%99%9F', '公車20、246、81至「澄清/弘光醫院（太原路）」；台鐵太原站約2.2公里（台中藍鯨官網）｜公車20、246至「弘光復健醫院」（iPlay）', '廣停5祥和停車場（建和路一段9號，593格）（台中藍鯨官網）｜iPlay登錄「無停車場」', 'iPlay登錄無無障礙設施（2021年存檔資料）', null, 'artificial'),
  ('nantun-artificial-turf', '南屯人工草皮練習場', null, '臺中市南屯區益豐路三段', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E5%8D%97%E5%B1%AF%E4%BA%BA%E5%B7%A5%E8%8D%89%E7%9A%AE%E7%B7%B4%E7%BF%92%E5%A0%B4%20%E8%87%BA%E4%B8%AD%E5%B8%82%E5%8D%97%E5%B1%AF%E5%8D%80%E7%9B%8A%E8%B1%90%E8%B7%AF%E4%B8%89%E6%AE%B5', null, null, null, null, 'artificial'),
  ('nanzi-football-field', '楠梓足球場', null, '高雄市楠梓區高雄大學路及援中路口', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E6%A5%A0%E6%A2%93%E8%B6%B3%E7%90%83%E5%A0%B4%20%E9%AB%98%E9%9B%84%E5%B8%82%E6%A5%A0%E6%A2%93%E5%8D%80', '公共自行車站「楠梓文中足球場」（維基百科線索）', '設有停車場（高雄市自治法規）；收費資訊查無', null, null, 'mixed'),
  ('tainan-municipal-football-stadium', '台南市立足球場', null, '台南市南區體育路10號', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E5%8F%B0%E5%8D%97%E5%B8%82%E7%AB%8B%E8%B6%B3%E7%90%83%E5%A0%B4%20%E5%8F%B0%E5%8D%97%E5%B8%82%E5%8D%97%E5%8D%80%E9%AB%94%E8%82%B2%E8%B7%AF10%E8%99%9F', null, null, null, 2000, null),
  ('fju-football-field', '輔仁大學足球場', null, '新北市新莊區中正路510號', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E8%BC%94%E4%BB%81%E5%A4%A7%E5%AD%B8%E8%B6%B3%E7%90%83%E5%A0%B4%20%E6%96%B0%E5%8C%97%E5%B8%82%E6%96%B0%E8%8E%8A%E5%8D%80%E4%B8%AD%E6%AD%A3%E8%B7%AF510%E8%99%9F', null, null, null, null, null),
  ('xizhi-sports-ground', '汐止綜合運動場', null, '221新北市汐止區秀峰里忠孝東路9號', null, 25.06537, 121.65842, 'https://www.google.com/maps/search/?api=1&query=%E6%B1%90%E6%AD%A2%E7%B6%9C%E5%90%88%E9%81%8B%E5%8B%95%E5%A0%B4%20%E6%96%B0%E5%8C%97%E5%B8%82%E6%B1%90%E6%AD%A2%E5%8D%80%E5%BF%A0%E5%AD%9D%E6%9D%B1%E8%B7%AF9%E8%99%9F', '汐止火車站西出口步行約5分鐘；公車605（新台五線）、675、678、907、藍15、內科通勤專車7、1031、F901、F905、F906、F912A、F912B、F915；低地板公車605、藍15', '智興立體停車場（404格，每小時30元）；汐止國民運動中心停車場（96格，每小時30元）', null, null, 'artificial'),
  ('taipei-municipal-stadium', '臺北田徑場', null, '10549臺北市松山區敦化北路3號', null, 25.04958, 121.55173, 'https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E7%94%B0%E5%BE%91%E5%A0%B4%20%E8%87%BA%E5%8C%97%E5%B8%82%E6%9D%BE%E5%B1%B1%E5%8D%80%E6%95%A6%E5%8C%96%E5%8C%97%E8%B7%AF3%E8%99%9F', null, null, null, 20000, null),
  ('hsinchu-county-second-stadium', '新竹縣第二運動場', null, '竹北市莊敬一路2號', null, null, null, 'https://www.google.com/maps/search/?api=1&query=%E6%96%B0%E7%AB%B9%E7%B8%A3%E7%AC%AC%E4%BA%8C%E9%81%8B%E5%8B%95%E5%A0%B4%20%E7%AB%B9%E5%8C%97%E5%B8%82%E8%8E%8A%E6%95%AC%E4%B8%80%E8%B7%AF2%E8%99%9F', null, null, null, 2500, null)
on conflict (slug) do update set
  name_zh = coalesce(excluded.name_zh, public_venues.name_zh),
  name_en = coalesce(excluded.name_en, public_venues.name_en),
  address_zh = coalesce(excluded.address_zh, public_venues.address_zh),
  address_en = coalesce(excluded.address_en, public_venues.address_en),
  lat = coalesce(excluded.lat, public_venues.lat),
  lng = coalesce(excluded.lng, public_venues.lng),
  map_url = coalesce(excluded.map_url, public_venues.map_url),
  transit_zh = coalesce(excluded.transit_zh, public_venues.transit_zh),
  parking_zh = coalesce(excluded.parking_zh, public_venues.parking_zh),
  accessibility_zh = coalesce(excluded.accessibility_zh, public_venues.accessibility_zh),
  capacity = coalesce(excluded.capacity, public_venues.capacity),
  surface = coalesce(excluded.surface, public_venues.surface)
where (public_venues.name_zh, public_venues.name_en, public_venues.address_zh, public_venues.address_en, public_venues.lat, public_venues.lng, public_venues.map_url, public_venues.transit_zh, public_venues.parking_zh, public_venues.accessibility_zh, public_venues.capacity, public_venues.surface)
  is distinct from (coalesce(excluded.name_zh, public_venues.name_zh), coalesce(excluded.name_en, public_venues.name_en), coalesce(excluded.address_zh, public_venues.address_zh), coalesce(excluded.address_en, public_venues.address_en), coalesce(excluded.lat, public_venues.lat), coalesce(excluded.lng, public_venues.lng), coalesce(excluded.map_url, public_venues.map_url), coalesce(excluded.transit_zh, public_venues.transit_zh), coalesce(excluded.parking_zh, public_venues.parking_zh), coalesce(excluded.accessibility_zh, public_venues.accessibility_zh), coalesce(excluded.capacity, public_venues.capacity), coalesce(excluded.surface, public_venues.surface));

-- Clubs (8). crest_permission stays as set in admin (new rows: unknown); no crest paths. --
insert into public.clubs (slug, name_zh, name_ja, name_en, short_zh, short_en, abbr, home_venue_id, website_url, instagram_url, facebook_url, youtube_url, is_self)
values
  ('taichung-futuro', '台中FUTURO', null, 'Taichung Futuro FC', '台中FUTURO', null, 'FUT', (select id from public.public_venues where slug = 'xitun-football-field'), 'https://futurofootball.wixsite.com/home', 'https://www.instagram.com/futuro.football/', 'https://www.facebook.com/FUTURO.TAIWAN/', null, true),
  ('taipower', '台灣電力', null, null, '台電', null, 'TPC', (select id from public.public_venues where slug = 'nanzi-football-field'), null, null, 'https://www.facebook.com/TaiPowerCompanyFC/', null, false),
  ('kaohsiung-attackers', '高雄先鋒', null, null, '高雄先鋒', null, 'KAFC', (select id from public.public_venues where slug = 'nanzi-football-field'), 'https://www.kaohsiungattackersfc.com/AttackersFC/tw/intro', 'https://www.instagram.com/attackersfc_men/', null, null, false),
  ('tatung', '大同石虎', null, null, '大同石虎', null, 'TTFC', (select id from public.public_venues where slug = 'fju-football-field'), 'https://tatungfc.oen.tw/', 'https://www.instagram.com/tatungfc/', 'https://www.facebook.com/FCTATUNG', null, false),
  ('ac-taipei', '陽信北競', null, 'Sunny Bank AC Taipei', '陽信北競', 'SAC', 'SAC', (select id from public.public_venues where slug = 'xizhi-sports-ground'), 'https://actaipei.com/', 'https://www.instagram.com/athletic_club_taipei/', 'https://www.facebook.com/athleticclubtaipei', 'https://www.youtube.com/channel/UCvRQvspKfMUSJPWxpW5PqHg', false),
  ('hang-yuan', '新北航源', null, null, '新北航源', null, 'HYFC', (select id from public.public_venues where slug = 'fju-football-field'), null, 'https://www.instagram.com/hang_yuan_fc/', 'https://www.facebook.com/HANGYUANFC/', null, false),
  ('tainan-tsg', '南市台鋼', null, null, '南市台鋼', null, 'TSG', (select id from public.public_venues where slug = 'tainan-municipal-football-stadium'), null, null, 'https://www.facebook.com/football.tainan.taiwan', null, false),
  ('taichung-rock', '台中磐石', null, 'Taichung Rock FC', '台中磐石', null, 'TCR', (select id from public.public_venues where slug = 'xitun-football-field'), 'https://www.tcrfc.tw/', 'https://www.instagram.com/tcr_fc_2024/', 'https://www.facebook.com/TCRFC2024', 'https://www.youtube.com/@TCRFC-2024', false)
on conflict (slug) do update set
  name_zh = coalesce(excluded.name_zh, clubs.name_zh),
  name_ja = coalesce(excluded.name_ja, clubs.name_ja),
  name_en = coalesce(excluded.name_en, clubs.name_en),
  short_zh = coalesce(excluded.short_zh, clubs.short_zh),
  short_en = coalesce(excluded.short_en, clubs.short_en),
  abbr = coalesce(excluded.abbr, clubs.abbr),
  home_venue_id = coalesce(excluded.home_venue_id, clubs.home_venue_id),
  website_url = coalesce(excluded.website_url, clubs.website_url),
  instagram_url = coalesce(excluded.instagram_url, clubs.instagram_url),
  facebook_url = coalesce(excluded.facebook_url, clubs.facebook_url),
  youtube_url = coalesce(excluded.youtube_url, clubs.youtube_url),
  is_self = coalesce(excluded.is_self, clubs.is_self)
where (clubs.name_zh, clubs.name_ja, clubs.name_en, clubs.short_zh, clubs.short_en, clubs.abbr, clubs.home_venue_id, clubs.website_url, clubs.instagram_url, clubs.facebook_url, clubs.youtube_url, clubs.is_self)
  is distinct from (coalesce(excluded.name_zh, clubs.name_zh), coalesce(excluded.name_ja, clubs.name_ja), coalesce(excluded.name_en, clubs.name_en), coalesce(excluded.short_zh, clubs.short_zh), coalesce(excluded.short_en, clubs.short_en), coalesce(excluded.abbr, clubs.abbr), coalesce(excluded.home_venue_id, clubs.home_venue_id), coalesce(excluded.website_url, clubs.website_url), coalesce(excluded.instagram_url, clubs.instagram_url), coalesce(excluded.facebook_url, clubs.facebook_url), coalesce(excluded.youtube_url, clubs.youtube_url), coalesce(excluded.is_self, clubs.is_self));

-- First-team fixtures, TFPL 2026/27 (21) ----------------------------------------------
create temporary table futuro_fixture_import (
  round_no integer primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  title text not null,
  opponent text not null,
  opponent_club_slug text,
  side public.match_side not null,
  venue_slug text,
  location text,
  status public.match_public_status not null,
  club_score integer,
  opponent_score integer,
  replay_url text,
  replay_video_id text,
  video_title text
) on commit drop;

insert into futuro_fixture_import values
  (1, '2026-09-13T19:00:00+08:00', '2026-09-13T21:30:00+08:00', '台企甲 第1輪 vs 大同石虎', '大同石虎', 'tatung', 'home', 'xitun-football-field', '台中西屯足球場', 'completed', 0, 1, 'https://www.youtube.com/watch?v=BX5z_31ePNk', 'BX5z_31ePNk', '2026/27台灣企業甲級足球聯賽 第1輪 場次02：台中FUTURO vs 大同石虎'),
  (2, '2026-09-20T19:30:00+08:00', '2026-09-20T22:00:00+08:00', '台企甲 第2輪 vs 高雄先鋒', '高雄先鋒', 'kaohsiung-attackers', 'home', 'xitun-football-field', '台中西屯足球場', 'completed', 0, 2, 'https://www.youtube.com/watch?v=2xp137k-j2c', '2xp137k-j2c', '2026/27台灣企業甲級足球聯賽 第2輪 場次07：台中FUTURO vs 高雄先鋒'),
  (3, '2026-10-11T15:30:00+08:00', '2026-10-11T18:00:00+08:00', '台企甲 第3輪 vs 台灣電力', '台灣電力', 'taipower', 'away', 'nanzi-football-field', '楠梓足球場', 'scheduled', null, null, null, null, null),
  (4, '2026-10-18T16:00:00+08:00', '2026-10-18T18:30:00+08:00', '台企甲 第4輪 vs 陽信北競', '陽信北競', 'ac-taipei', 'home', 'taiyuan-football-field', '太原足球場', 'scheduled', null, null, null, null, null),
  (5, '2026-10-25T19:00:00+08:00', '2026-10-25T21:30:00+08:00', '台企甲 第5輪 vs 台中磐石', '台中磐石', 'taichung-rock', 'away', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (6, '2026-11-01T18:30:00+08:00', '2026-11-01T21:00:00+08:00', '台企甲 第6輪 vs 南市台鋼', '南市台鋼', 'tainan-tsg', 'away', 'tainan-municipal-football-stadium', '台南市立足球場', 'scheduled', null, null, null, null, null),
  (7, '2026-11-22T15:30:00+08:00', '2026-11-22T18:00:00+08:00', '台企甲 第7輪 vs 新北航源', '新北航源', 'hang-yuan', 'home', 'taiyuan-football-field', '太原足球場', 'scheduled', null, null, null, null, null),
  (8, '2026-11-29T16:00:00+08:00', '2026-11-29T18:30:00+08:00', '台企甲 第8輪 vs 大同石虎', '大同石虎', 'tatung', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (9, '2026-12-06T19:00:00+08:00', '2026-12-06T21:30:00+08:00', '台企甲 第9輪 vs 高雄先鋒', '高雄先鋒', 'kaohsiung-attackers', 'away', 'nanzi-football-field', '楠梓足球場', 'scheduled', null, null, null, null, null),
  (10, '2026-12-13T16:00:00+08:00', '2026-12-13T18:30:00+08:00', '台企甲 第10輪 vs 台灣電力', '台灣電力', 'taipower', 'home', 'nantun-artificial-turf', '南屯人工草皮練習場', 'scheduled', null, null, null, null, null),
  (11, '2027-01-24T19:00:00+08:00', '2027-01-24T21:30:00+08:00', '台企甲 第11輪 vs 陽信北競', '陽信北競', 'ac-taipei', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (12, '2027-01-31T19:00:00+08:00', '2027-01-31T21:30:00+08:00', '台企甲 第12輪 vs 台中磐石', '台中磐石', 'taichung-rock', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (13, '2027-02-21T16:00:00+08:00', '2027-02-21T18:30:00+08:00', '台企甲 第13輪 vs 南市台鋼', '南市台鋼', 'tainan-tsg', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (14, '2027-02-28T19:00:00+08:00', '2027-02-28T21:30:00+08:00', '台企甲 第14輪 vs 新北航源', '新北航源', 'hang-yuan', 'away', 'fju-football-field', '輔仁大學足球場', 'scheduled', null, null, null, null, null),
  (15, '2027-03-07T16:00:00+08:00', '2027-03-07T18:30:00+08:00', '台企甲 第15輪 vs 大同石虎', '大同石虎', 'tatung', 'away', 'fju-football-field', '輔仁大學足球場', 'scheduled', null, null, null, null, null),
  (16, '2027-03-14T19:00:00+08:00', '2027-03-14T21:30:00+08:00', '台企甲 第16輪 vs 高雄先鋒', '高雄先鋒', 'kaohsiung-attackers', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (17, '2027-03-21T19:00:00+08:00', '2027-03-21T21:30:00+08:00', '台企甲 第17輪 vs 台灣電力', '台灣電力', 'taipower', 'away', 'nanzi-football-field', '楠梓足球場', 'scheduled', null, null, null, null, null),
  (18, '2027-04-11T16:00:00+08:00', '2027-04-11T18:30:00+08:00', '台企甲 第18輪 vs 陽信北競', '陽信北競', 'ac-taipei', 'away', 'xizhi-sports-ground', '汐止綜合運動場', 'scheduled', null, null, null, null, null),
  (19, '2027-04-18T19:00:00+08:00', '2027-04-18T21:30:00+08:00', '台企甲 第19輪 vs 台中磐石', '台中磐石', 'taichung-rock', 'away', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null),
  (20, '2027-04-25T18:30:00+08:00', '2027-04-25T21:00:00+08:00', '台企甲 第20輪 vs 南市台鋼', '南市台鋼', 'tainan-tsg', 'away', 'tainan-municipal-football-stadium', '台南市立足球場', 'scheduled', null, null, null, null, null),
  (21, '2027-05-02T19:30:00+08:00', '2027-05-02T22:00:00+08:00', '台企甲 第21輪 vs 新北航源', '新北航源', 'hang-yuan', 'home', 'xitun-football-field', '台中西屯足球場', 'scheduled', null, null, null, null, null);

do $$
declare
  v_team uuid := (select id from public.teams where kind = 'competition_team' and layer_key = 'senior' and age_band = 'senior' and status = 'active');
  v_season uuid := (select id from public.seasons where label = '2026/27');
  v_competition uuid := (select id from public.competitions where slug = 'tfpl');
  f record;
  v_session uuid;
  v_club uuid;
  v_venue uuid;
  v_created integer := 0;
  v_filled integer := 0;
begin
  for f in select * from futuro_fixture_import order by round_no loop
    v_club := (select id from public.clubs where slug = f.opponent_club_slug);
    v_venue := (select id from public.public_venues where slug = f.venue_slug);

    -- Same round of this season and competition, else same kickoff, for the first team.
    select s.id into v_session
    from public.training_sessions s
    join public.match_publications p on p.session_id = s.id
    where s.team_id = v_team
      and s.deleted_at is null
      and public.is_match_session_kind(s.kind)
      and (
        (p.season_id = v_season and p.competition_id = v_competition and p.round_no = f.round_no)
        or s.starts_at = f.starts_at
      )
    order by (p.round_no is not distinct from f.round_no) desc, s.created_at
    limit 1;

    if v_session is null then
      insert into public.training_sessions (team_id, title, kind, starts_at, ends_at, location)
      values (v_team, f.title, 'league', f.starts_at, f.ends_at, f.location)
      returning id into v_session;

      insert into public.match_publications (
        session_id, opponent, opponent_club_id, side, is_published, public_status,
        club_score, opponent_score, result_entered_at,
        public_venue_id, season_id, competition_id, round_no,
        replay_url, replay_video_id, video_title
      ) values (
        v_session, f.opponent, v_club, f.side, false, f.status,
        f.club_score, f.opponent_score, case when f.status = 'completed' then f.ends_at end,
        v_venue, v_season, v_competition, f.round_no,
        f.replay_url, f.replay_video_id, f.video_title
      );
      v_created := v_created + 1;
    else
      -- Existing match: only fill what is still empty; never overwrite admin edits.
      update public.match_publications p set
        opponent = coalesce(p.opponent, f.opponent),
        opponent_club_id = coalesce(p.opponent_club_id, v_club),
        public_venue_id = coalesce(p.public_venue_id, v_venue),
        season_id = coalesce(p.season_id, v_season),
        competition_id = coalesce(p.competition_id, v_competition),
        round_no = coalesce(p.round_no, f.round_no)
      where p.session_id = v_session
        and (
          (p.opponent is null and f.opponent is not null)
          or (p.opponent_club_id is null and v_club is not null)
          or (p.public_venue_id is null and v_venue is not null)
          or p.season_id is null or p.competition_id is null or p.round_no is null
        );
      if found then v_filled := v_filled + 1; end if;

      update public.match_publications p set
        public_status = 'completed',
        club_score = f.club_score,
        opponent_score = f.opponent_score,
        result_entered_at = f.ends_at
      where p.session_id = v_session
        and f.status = 'completed'
        and p.public_status = 'scheduled'
        and p.club_score is null;
      if found then v_filled := v_filled + 1; end if;

      update public.match_publications p set
        replay_url = f.replay_url,
        replay_video_id = f.replay_video_id,
        video_title = coalesce(p.video_title, f.video_title)
      where p.session_id = v_session
        and f.replay_video_id is not null
        and p.replay_video_id is null
        and p.replay_url is null;
      if found then v_filled := v_filled + 1; end if;
    end if;
  end loop;
  raise notice 'futuro fixtures: % created, % filled in', v_created, v_filled;
end
$$;

-- Standings (16) ------------------------------------------------------------------
insert into public.standings (season_id, competition_id, after_round, club_id, rank, played, won, drawn, lost, goals_for, goals_against, points, is_official, source_url, fetched_at)
select se.id, co.id, v.after_round, cl.id, v.rank, v.played, v.won, v.drawn, v.lost, v.goals_for, v.goals_against, v.points, v.is_official, v.source_url, v.fetched_at::timestamptz
from (values
  ('kaohsiung-attackers', 1, 1, 1, 1, 0, 0, 5, 2, 3, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('taipower', 1, 2, 1, 1, 0, 0, 1, 0, 3, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('tatung', 1, 2, 1, 1, 0, 0, 1, 0, 3, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('hang-yuan', 1, 4, 1, 0, 1, 0, 1, 1, 1, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('tainan-tsg', 1, 4, 1, 0, 1, 0, 1, 1, 1, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('ac-taipei', 1, 6, 1, 0, 0, 1, 0, 1, 0, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('taichung-futuro', 1, 6, 1, 0, 0, 1, 0, 1, 0, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('taichung-rock', 1, 8, 1, 0, 0, 1, 2, 5, 0, false, 'https://www.ctfa.com.tw/2026-a', '2026-10-03T00:00:00+08:00'),
  ('kaohsiung-attackers', 2, 1, 2, 2, 0, 0, 7, 2, 6, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('taipower', 2, 2, 2, 2, 0, 0, 4, 1, 6, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('tatung', 2, 3, 2, 1, 1, 0, 1, 0, 4, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('ac-taipei', 2, 4, 2, 1, 0, 1, 2, 1, 3, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('hang-yuan', 2, 5, 2, 0, 2, 0, 1, 1, 2, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('tainan-tsg', 2, 6, 2, 0, 1, 1, 1, 3, 1, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('taichung-futuro', 2, 7, 2, 0, 0, 2, 0, 3, 0, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00'),
  ('taichung-rock', 2, 8, 2, 0, 0, 2, 3, 8, 0, true, 'https://www.ctfa.com.tw/2026-a/ranking/67-tfpl2026/0.html', '2026-10-03T00:00:00+08:00')
) as v(club_slug, after_round, rank, played, won, drawn, lost, goals_for, goals_against, points, is_official, source_url, fetched_at)
join public.clubs cl on cl.slug = v.club_slug
cross join (select id from public.seasons where label = '2026/27') se
cross join (select id from public.competitions where slug = 'tfpl') co
on conflict (season_id, competition_id, after_round, club_id) do update set
  rank = excluded.rank,
  played = excluded.played,
  won = excluded.won,
  drawn = excluded.drawn,
  lost = excluded.lost,
  goals_for = excluded.goals_for,
  goals_against = excluded.goals_against,
  points = excluded.points,
  is_official = excluded.is_official,
  source_url = excluded.source_url,
  fetched_at = excluded.fetched_at
where (standings.rank, standings.played, standings.won, standings.drawn, standings.lost, standings.goals_for, standings.goals_against, standings.points, standings.is_official, standings.source_url, standings.fetched_at)
  is distinct from (excluded.rank, excluded.played, excluded.won, excluded.drawn, excluded.lost, excluded.goals_for, excluded.goals_against, excluded.points, excluded.is_official, excluded.source_url, excluded.fetched_at);

commit;
